### ISSUE TITLE
meta: spam protection tracking

### ISSUE THREAD

**Issue by insertish** [revoltchat/revolt#297]
- [ ] https://github.com/revoltchat/api/issues/18
- [ ] (prepare to) fork backend (may block on https://github.com/revoltchat/quark/issues/10)
- [ ] build 2-layer captcha service
- [x] tangentially related, swap keydb with redis
